dijkstra_node:
  ros__parameters:
    # Topics
    is_antiClockwise: false
    costmap_topic: "/inflated_costmap"
    goal_topic: "/clicked_point"
    path_topic: "/pp_path"
    visited_map_topic: "/visited_map"

    # Frames
    map_frame: "map"
    base_frame: "ego_racecar/base_link"

    # Planning parameters
    planning:
      use_8_connected: true
      base_movement_cost: 10
      diagonal_movement_cost: 14
      interpolation_resolution: 0.35  # meters
      coordinates_tolerance: 1  # cells

    # Occupancy thresholds
    occupancy:
      occupied_threshold: 99
      free_threshold: 0

    # Logging
    log_level: "INFO"
